class Post < ApplicationRecord
    validates(
        :author,
        presence: { message: "author must exist" },
        uniqueness: true,
        length: { minimum: 3 }
    )
    validates(
        :body,
        presence: { message: "must exist" },
        length: { minimum: 20 }
    )
end

# Model => A Rails Model is a Ruby class that can add database records (think of whole rows in an Excel table), find particular data you're looking for, update that data, or remove data. ... Rails contains a model generator, which you can use via your command line, as long as you're in a Rails app already. in this we add some vadilations to our app like author must have altleast 3 alphabets and body should have atleast 20 alphabets.It is generated by rails g model <Name of the model>